name: CI
on: [push]
jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    steps:
      - name: Pull and build
        run: |
          cd ~/barbarian-bot/
          git fetch
          git checkout master
          git pull
          npm install
          pm2 restart barbarian-bot